### PR TITLE
README: rename Lonvia to Waymarked Trails

### PR DESCRIPTION
**Pull request by hugovdm**
Lonvia's routes are served from waymarkedtrails.org
- https://wiki.openstreetmap.org/wiki/User:Lonvia

### CODE REVIEW

**Comment by hugovdm** [comment]
I haven't tried out your app yet, I was just looking into what it supports, and wondered what "Lonvia routes" were.

**Comment by hugovdm** [comment]
I'm also curious why it's only on F-Droid and not also on Google Play. (I have a friend who would provide his apps only via F-Droid out of matter of principle, I wondered if that's the case here, or if there are other/technical reasons.)

Might it make sense to add mention of the rationale in the README? Or is it best left unstated?

**Comment by hugovdm** [comment]
Having actually started using the app, I now know "Lonvia" is mentioned in many places, not just the README. I think that should be changed all together, or not at all - I'm closing/cancelling this PR. :)

**Comment by Pygmalion69** [comment]
The app is not on Play because it is a hobby project for which I really don't have much time and it is certainly not worth maintaining just to meet the growing amount of requirements and conditions, while running the risk of violating new policies over and over again.

**Pull request closed without merging**
